name: REFRESH

on:
  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name Voice Amplifier""
          git config user.email "voice@amplifier"

      - name: Run update script
        run: |
          bash mirror.sh

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add .
          git commit -m "Automatic data update"
          git push
