name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name Voice Amplifier""
          git config user.email "voice@amplifier"

      - name: Run update script
        run: |
          bash mirror.sh

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add .
          git commit -m "Automatic data update"
          git push

      - name: Run a one-line script
        run: echo Hello, world!

